# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a4953bd6fde937f51095aebf0b71fadaa3ef9c36040151009fc570e88782486962ff873c1c01ca6d356dd38b9950dd9906936359c640043651fd9a608c2612d

test:
  secret_key_base: 0949ef23262c51818ee009a2eebd06394508431264e817843c9c347bda28c147dc26ef0dd41cf140343820b59c3ecaffc33cacdabd453a6586c3bf6d9907dca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
